url: https://ankur-igsa-pitt.github.io
baseurl: /home/

# Site settings
title: ANKUR IGSA - University of Pittsburgh
email: pitt.ankur@gmail.com
description: "Write an awesome description for your new site here. 
You can edit this line in _config.yml. 
It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Vijayendra Kumar
  pic: 20
  position: President
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: stack-overflow
  #     url: #

- name: Arun Balajiee
  pic: 0
  position: Vice President

- name: Shreya Singh
  pic: 20
  position: General Secretary

- name: Ashish Jha
  pic: 20
  position: Business Manager

- name: Shanim Manzoor
  pic: 20
  position: Event Manager

- name: Aishwarya Vasudevan
  pic: 5
  position: Event Manager

- name:
  pic: 
  position:

- name: Kavita Sah
  pic: 20
  position: Public Relations

- name:
  pic: 
  position:

- name: Karthik Jadala
  pic: 20
  position: Public Relations

- name: Sanzil Madye
  pic: 20
  position: Cultural Manager

- name: Vipul Agrawal
  pic: 20
  position: Cultural Manager


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
